export const ACS = {
  BOND_LENGTH: 40,
  LINE_WIDTH: 0.6,
  BOLD_WIDTH: 2.0,
  HASH_SPACING: 2.5,
  BOND_SPACING: 0.18,
  AROMATIC_CIRCLE_RATIO: 0.75,
  CHAIN_ANGLE: 120,
  WEDGE_WIDTH_RATIO: 0.15,
  ATOM_FONT_SIZE: 10,
  MARGIN_WIDTH: 1.6,
};
